blank_issues_enabled: false
contact_links:
  - name: Provider Documentation
    url: https://registry.terraform.io/providers/emanuelbesliu/tplink-omada/latest/docs
    about: Browse the provider documentation on the Terraform Registry
